import type { Category, Task } from './types';
import { uid } from './utils';

function daysFromNow(days: number, hour = 9, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

export const defaultCategories: Category[] = [
  { id: 'prace', name: 'Práce', color: '#3E82F7' },
  { id: 'osobni', name: 'Osobní', color: '#6C5CE7' },
  { id: 'nakupy', name: 'Nákupy', color: '#2ED573' },
  { id: 'fitko', name: 'Fitko', color: '#FF9F43' },
  { id: 'projekty', name: 'Projekty', color: '#FF4B4B' },
];

export const dummyTasks: Task[] = [
  {
    id: uid(),
    title: 'Sraz s týmem v 10:30',
    description: 'Ranní standup, projít status úkolů a naplánovat sprint.',
    category: 'prace',
    priority: 'high',
    dueDate: daysFromNow(0, 10, 30),
    subtasks: [
      { id: uid(), title: 'Aktualizovat board', done: true },
      { id: uid(), title: 'Připravit poznámky', done: false },
      { id: uid(), title: 'Domluvit další schůzku', done: false },
    ],
    recurrence: 'weekly',
    done: false,
    pinned: true,
    createdAt: daysFromNow(-3),
    completedAt: null,
  },
  {
    id: uid(),
    title: 'Připravit prezentaci pro klienta',
    description: 'Upravit slide deck, přidat grafy z minulého čtvrtletí a zkontrolovat s týmem.',
    category: 'prace',
    priority: 'high',
    dueDate: daysFromNow(0, 14, 30),
    subtasks: [
      { id: uid(), title: 'Aktualizovat finanční data', done: true },
      { id: uid(), title: 'Přidat grafy růstu', done: true },
      { id: uid(), title: 'Korektura textů', done: false },
      { id: uid(), title: 'Zkoušková prezentace', done: false },
    ],
    recurrence: 'once',
    done: false,
    pinned: false,
    createdAt: daysFromNow(-3),
    completedAt: null,
  },
  {
    id: uid(),
    title: 'Nákup na víkend',
    description: 'Velký nákup do zásoby pro celou rodinu.',
    category: 'nakupy',
    priority: 'medium',
    dueDate: daysFromNow(1, 17, 0),
    subtasks: [
      { id: uid(), title: 'Chléb a pečivo', done: false },
      { id: uid(), title: 'Mléčné výrobky', done: false },
      { id: uid(), title: 'Zelenina a ovoce', done: false },
      { id: uid(), title: 'Maso', done: false },
      { id: uid(), title: 'Nápoje', done: false },
    ],
    recurrence: 'weekly',
    done: false,
    pinned: false,
    createdAt: daysFromNow(-1),
    completedAt: null,
  },
  {
    id: uid(),
    title: 'Ranní běh v parku v 6:30',
    description: '5 km klidným tempem, protáhnout se po cvičení.',
    category: 'fitko',
    priority: 'low',
    dueDate: daysFromNow(0, 6, 30),
    subtasks: [
      { id: uid(), title: 'Rozcvička', done: false },
      { id: uid(), title: 'Běh 5 km', done: false },
      { id: uid(), title: 'Protažení', done: false },
    ],
    recurrence: 'daily',
    done: false,
    pinned: false,
    createdAt: daysFromNow(-5),
    completedAt: null,
  },
  {
    id: uid(),
    title: 'Dokončit návrh mobilní aplikace',
    description: 'High-fidelity prototyp v Figmě, připravit handoff pro vývojáře.',
    category: 'projekty',
    priority: 'high',
    dueDate: daysFromNow(3, 12, 0),
    subtasks: [
      { id: uid(), title: 'Domovská obrazovka', done: true },
      { id: uid(), title: 'Detail úkolu', done: true },
      { id: uid(), title: 'Nastavení', done: true },
      { id: uid(), title: 'Onboarding flow', done: false },
      { id: uid(), title: 'Dark mode varianty', done: false },
    ],
    recurrence: 'once',
    done: false,
    pinned: false,
    createdAt: daysFromNow(-7),
    completedAt: null,
  },
  {
    id: uid(),
    title: 'Zavolat babičce v 18:00',
    description: 'Zeptat se na zdraví a domluvit víkendovou návštěvu.',
    category: 'osobni',
    priority: 'medium',
    dueDate: daysFromNow(0, 18, 0),
    subtasks: [],
    recurrence: 'weekly',
    done: false,
    pinned: false,
    createdAt: daysFromNow(-2),
    completedAt: null,
  },
  {
    id: uid(),
    title: 'Revidovat rozpočet na příští měsíc',
    description: 'Projít výdaje, naplánovat úspory a fixní náklady.',
    category: 'osobni',
    priority: 'low',
    dueDate: daysFromNow(5, 20, 0),
    subtasks: [
      { id: uid(), title: 'Stáhnout výpisy', done: false },
      { id: uid(), title: 'Rozdělit do kategorií', done: false },
    ],
    recurrence: 'monthly',
    done: false,
    pinned: false,
    createdAt: daysFromNow(-1),
    completedAt: null,
  },
  {
    id: uid(),
    title: 'Odpovědět na e-maily od týmu',
    description: 'Fronta nevyřízených zpráv ze včerejška.',
    category: 'prace',
    priority: 'medium',
    dueDate: daysFromNow(-1, 10, 0),
    subtasks: [
      { id: uid(), title: 'Odpovědět Petru', done: true },
      { id: uid(), title: 'Odpovědět Lence', done: true },
      { id: uid(), title: 'Přeposlat report', done: true },
    ],
    recurrence: 'once',
    done: true,
    pinned: false,
    createdAt: daysFromNow(-2),
    completedAt: daysFromNow(-1, 11, 0),
  },
  {
    id: uid(),
    title: 'Objednat nové pneumatiky',
    description: 'Sezónní výměna na zimní, porovnat ceny online.',
    category: 'osobni',
    priority: 'low',
    dueDate: daysFromNow(7, 9, 0),
    subtasks: [],
    recurrence: 'once',
    done: false,
    pinned: false,
    createdAt: daysFromNow(-4),
    completedAt: null,
  },
];
